SELECT Yogurt.CART_ID
FROM (SELECT CART_ID
     FROM CART_PRODUCTS
     WHERE NAME = 'Yogurt') AS Yogurt,
     (SELECT CART_ID
     FROM CART_PRODUCTS
     WHERE NAME = 'Milk') AS Milk
WHERE Yogurt.CART_ID = Milk.CART_ID